# Python Django
# Test a Django project on multiple versions of Python.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  SONAR_ORGANIZATION: 'afbm66'
  SONAR_TOKEN: 'afbm66-1'


strategy:
  matrix:
    Python311:
      PYTHON_VERSION: '3.11'

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'Django-Beginners'
    organization: '$(SONAR_ORGANIZATION)'
    scannerMode: 'CLI'
    configMode: 'automatic'
    cliProjectKey: 'c8716aa2ef1c2f65480487602e2277d900594d2b'
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(PYTHON_VERSION)'
    architecture: 'x64'

- task: PythonScript@0
  displayName: 'Export project path'
  inputs:
    scriptSource: 'inline'
    script: |
      """Search all subdirectories for `manage.py`."""
      from glob import iglob
      from os import path
      # Python >= 3.5
      manage_py = next(iglob(path.join('**', 'manage.py'), recursive=True), None)
      if not manage_py:
          raise SystemExit('Could not find a Django project')
      project_location = path.dirname(path.abspath(manage_py))
      print('Found Django project in', project_location)
      print('##vso[task.setvariable variable=projectRoot]{}'.format(project_location))

- script: |
    pushd '$(projectRoot)'
    echo "Current directory: $(pwd)"
    ls  # List files in the current directory
  displayName: 'Change to the working directory'
- script: |
    python -m pip install --upgrade pip setuptools wheel
    pip install -r ./demo-code/requirements.txt
    # pip install -r requirements.txt
    pip install unittest-xml-reporting
    pip list
  displayName: 'Install prerequisites'

# Solución sugerida por Chat GPT para eliminar el error "Missing staticfiles..."
- script: |
    pushd '$(projectRoot)'
    python manage.py collectstatic --noinput
  displayName: 'Collect static files'

- script: |
    pushd '$(projectRoot)'
    # python manage.py test --testrunner xmlrunner.extra.djangotestrunner.XMLTestRunner --no-input
    python manage.py test #  relecloud --no-input
  displayName: 'Run tests'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: "**/TEST-*.xml"
    testRunTitle: 'Python $(PYTHON_VERSION)'
  condition: succeededOrFailed()
- task: SonarCloudAnalyze@1
  env:
    SONAR_ORGANIZATION: 'afbm66'
    SONAR_TOKEN: 'afbm66-1'

- task: SonarCloudPublish@1
  inputs: 
    pollingTimeoutSec: '300'
  env:
    SONAR_ORGANIZATION: 'afbm66'
    SONAR_TOKEN: 'afbm66-1'

# ****************************************************

# trigger:
# - main

# pool:
#   vmImage: ubuntu-latest
# strategy:
#   matrix:
#     Python38:
#       python.version: '3.8'
#     Python39:
#       python.version: '3.9'
#     Python310:
#       python.version: '3.10'

# steps:
# - task: UsePythonVersion@0
#   inputs:
#     versionSpec: '$(python.version)'
#   displayName: 'Use Python $(python.version)'

# - script: |
#     python -m pip install --upgrade pip
#     pip install -r requirements.txt
#   displayName: 'Install dependencies'

# - script: |
#     pip install pytest pytest-azurepipelines
#     pytest
#   displayName: 'pytest'